### ISSUE TITLE
Issue on page /pairwise/needleman.html

### ISSUE THREAD

**Issue by LinaAlHanbali** [statisticalbiotechnology/bibook#12]
I am not sure if this is an issue, however in the example 3.6.1 when filling in the cell on the second row, last column, shouldn't there be an arrow from the left as well (from -2 to -1) since that would give a score of -1 just like the diagonal arrow? If this is not an issue, my question is why is the score not -1, based on the score of the left cell plus the score for matching. 

![Skärmbild 2024-08-28 220820](https://github.com/user-attachments/assets/a0c6f8ee-d823-488b-bc46-e6b057d08bb9)

**Comment by AliSofia** [comment]
The score moving from the left is -3 not -1. The scores are determined by: 
<img width="296" alt="Skärmavbild 2024-08-29 kl  00 37 14" src="https://github.com/user-attachments/assets/d2b8b4c9-07e7-4f42-8c03-6de63f7925aa">
The value of the d-functions are then determined by the scoring system which in this case is: 
<img width="237" alt="Skärmavbild 2024-08-29 kl  00 49 31" src="https://github.com/user-attachments/assets/f6c231ab-6fba-4c66-a124-4949a85ba0eb">
We cannot add the match score to the value of the left cell since d(ai,-) and d(-,bj) always equal -1 according to the scoring system. This leaves us the scores: -3 from the left, -4 from above, and -1 diagonally. 

Hope this helped :)

**Comment by percolator** [comment]
Yes, @AliSofia is right! --Lukas
